-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."simulators" add column "expected_temperature_value" integer
--  not null;
