-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."algorithm_settings" add column "sensor_types" text
--  not null;
