version: '3.7'
services:
  example:
    container_name: iml-datasoft-nextjs-web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4202:3000'
