-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."simulators" add column "max_expected_sound_value" integer
--  null;
